blank_issues_enabled: true
contact_links:
  - name: Claiming namespace ownership
    url: https://github.com/EclipseFdn/open-vsx.org/issues/new/choose
    about: Claiming ownership of a namespace on open-vsx.org.
  - name: Remove extension request
    url: https://github.com/EclipseFdn/open-vsx.org/issues/new/choose
    about: Requesting to remove an extension hosted on open-vsx.org.
