name: Gradle Dependency Submission
on:
  push:
    branches:
      - master
jobs:
  dependency-submission:
    name: Gradle dependency submission
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse/openvsx'
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
          persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
      with:
        distribution: 'temurin'
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5
      with:
        dependency-graph: 'generate-submit-and-upload'
    - run: server/gradlew --no-daemon -p server assemble
      env:
        DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: 'productionRuntimeClasspath'
