name: CI

on: [push, pull_request]

env:
  SERVER_TAG: docker.pkg.github.com/eclipse/openvsx/openvsx-server
  SERVER_VERSION: snapshot
  WEB_UI_TAG: docker.pkg.github.com/eclipse/openvsx/openvsx-webui
  WEB_UI_VERSION: snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Set up Yarn
      run: npm install --global yarn
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/checkout@v2
    - name: Build CLI
      run: yarn --cwd cli
    - name: Build Web UI Image
      run: docker build -t $WEB_UI_TAG:$WEB_UI_VERSION webui
    - name: Run Server Tests
      run: server/gradlew --no-daemon -p server check
    - name: Build Server Image
      run: docker build -t $SERVER_TAG:$SERVER_VERSION server
    - name: Push Docker Images
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        docker push $SERVER_TAG:$SERVER_VERSION
        docker push $WEB_UI_TAG:$WEB_UI_VERSION
      if: github.repository == 'eclipse/openvsx' && github.ref == 'refs/heads/master'
