name: Release

on:
  release:
    types: [published]

env:
  SERVER_TAG: ghcr.io/eclipse/openvsx-server
  WEBUI_TAG: ghcr.io/eclipse/openvsx-webui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Image Version
      run: echo "IMAGE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - name: Build Web UI Image
      run: docker build -t $WEBUI_TAG:$IMAGE_VERSION webui
    - name: Build Server Image
      run: docker build -t $SERVER_TAG:$IMAGE_VERSION server
    - name: Push Docker Images
      run: |
        echo ${{ secrets.BOT_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push $SERVER_TAG:$IMAGE_VERSION
        docker push $WEBUI_TAG:$IMAGE_VERSION
